### PR TITLE
Added Streaming Response example

### PR DESCRIPTION
**Pull request by berfarah**
Hey @jodosha, added an example that I would use for a streaming response. I think a SSE example would be good too, but I don't have much experience with those.

### CODE REVIEW

**Comment by jodosha** [comment]
@berfarah Thank you, this looks good. Would you mind to describe which web servers work with it. From the description we communicate that WEBrick doesn't work, so we should provide a reliable alternative (aka standard) for this. What do you use?

**Comment by berfarah** [comment]
@jodosha I've added puma to the readme, though I believe unicorn, thin and passenger would work as well. Would you like to provide multiple options or just the one?

**Comment by joneslee85** [comment]
@berfarah I think we should stick to `puma`, as it is recommended on Heroku and elsewhere too

**Comment by berfarah** [comment]
@joneslee85 Sounds good. In the README I have now:
[Streaming does not work with WEBrick as it buffers its response. We recommend using `puma`, though you may find success with other servers ](https://github.com/lotus/controller/pull/129/files#diff-04c6e90faac2675aa89e2176d2eec7d8R953)

**Comment by joneslee85** [comment]
good to me

**Comment by jodosha** [comment]
@berfarah Thank you! :+1:

**Pull request merged**
