### PR TITLE
Added new callbacks to action.

### LINKED ISSUE #76: Ability to configure a filter in a specific position
Granted that one of @jodosha's goal was to keep callbacks as simple as possible, I have a case that I feel reveal a reasonable improvement.

Let's assume I have a filter called `authenticate!` that must be run on every action.

```ruby
class Show
  before :authenticate!

  def call(params)
  end
end
```

On a **very few actions** (that's one of the key conditions), let's say 10 out of 100, I need a specific validation to happen before the authenticate.

```ruby
class Index
  before :validate!, :authenticate!

  def call(params)
  end
end
```

I can indeed stick with the explicit example above, but that would mean I can't extract the `before :authenticate!` into a controller config, or a module.

Therefore, I wonder what do you think about providing a finer way to control where I want to add my filter. Right now, there's only a `Chain#add` method.

I propose to add something similar to

- `Chain#append(callback)`
- `Chain#prepend(callback)`
- `Chain#insert(before, callback)` (or `Chain#insert_before(before, callback)` and `Chain#insert_after(after, callback)`)

I can work on a patch, if we agree on naming and API.

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
Added prepend_before, prepend_after, append_before and append_after.

Closes #76

### CODE REVIEW

**Comment by jodosha** [comment]
@AlfonsoUceda This looks great for me. :+1:

**Comment by AlfonsoUceda** [comment]
I didn't introduce more tests, I think is enough

**Comment by jodosha** [comment]
@joneslee85 and @weppos Do you mind to review this?

**Comment by weppos** [comment]
One concern. I wonder if the primary method should be `append_before` and the alias `before`, rather than the opposite, for consistency with `prepend_before`.

**Comment by jodosha** [comment]
@weppos That was mine too. Now we're two people concerned with it. :+1: for this change.
If there isn't any stopping point, this should be released on tomorrow as `v0.3.2`.

**Comment by AlfonsoUceda** [comment]
ok @jodosha and @weppos I'm going to do that change ;) :+1: for the change

**Comment by joneslee85** [comment]
me like, me :+1:

**Comment by jodosha** [comment]
@AlfonsoUceda I've merged this, thank you! :+1:

**Comment by weppos** [comment]
Thanks @AlfonsoUceda for the work. :clap:

**Comment by AlfonsoUceda** [comment]
you welcome mates ;)

**Pull request merged**
